services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
flask:
    image: snickch/flask001:v2
    container_name: flask
    restart: always
    expose:
      - 5000
    volumes:
      - ./app:/app:ro
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
